# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

def fib(n):
  if n == 0: return n
  if n == 1: return n
  else: return fib(n-1) + fib(n-2)

def evenFibs(max):
  s = 0
  i = 0
  f = fib(i)
  while f <= max:
    if f%2 == 0: s += f
    i += 1
    f = fib(i)
  return s

print(evenFibs(4000000))
